# Generated by Django 4.0.3 on 2022-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('total_sqft', models.FloatField()),
                ('Rooms', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('balcony', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
